packages:
  - packages/*
  - services/*
  - frontend

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - isolated-vm
  - prisma
  - protobufjs
