import {
  Play,
  Square,
  Bot,
  Wrench,
  Cpu,
  GitFork,
  Shuffle,
  MessageSquare,
  Type,
  File,
  Repeat2,
  Github,
  MessageCircle,
  Phone,
  Terminal,
  HardDriveDownload,
  HardDriveUpload,
  Workflow,
  Network,
  Mail,
  Download,
  Braces,
  RefreshCcw,
  SplitSquareHorizontal,
  ListOrdered,
  FileText,
  type LucideIcon,
} from 'lucide-react';
import { NodeTypeId } from '@/types';
export type { NodeTypeId };

export interface NodeTypeMeta {
  id: NodeTypeId;
  label: string;
  labelFr: string;
  description: string;
  descriptionFr: string;
  icon: LucideIcon;
  color: string;
  bgColor: string;
  borderColor: string;
  defaultConfig: Record<string, unknown>;
}

export const NODE_TYPE_REGISTRY: NodeTypeMeta[] = [
  {
    id: 'START',
    label: 'Start',
    labelFr: 'Départ',
    description: 'Entry point of the workflow',
    descriptionFr: "Point d'entrée du workflow",
    icon: Play,
    color: 'text-emerald-500',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/40',
    defaultConfig: {},
  },
  {
    id: 'END',
    label: 'End',
    labelFr: 'Fin',
    description: 'Terminal node that ends the workflow',
    descriptionFr: 'Nœud terminal qui termine le workflow',
    icon: Square,
    color: 'text-rose-500',
    bgColor: 'bg-rose-500/10',
    borderColor: 'border-rose-500/40',
    defaultConfig: {},
  },
  {
    id: 'AGENT',
    label: 'Agent',
    labelFr: 'Agent',
    description: 'Run an AI agent',
    descriptionFr: 'Exécuter un agent IA',
    icon: Bot,
    color: 'text-violet-500',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/40',
    defaultConfig: { agentId: '', nodePrompt: '', outputFormat: 'text', outputKey: '', outputTemplate: '' },
  },
  {
    id: 'TOOL',
    label: 'Tool',
    labelFr: 'Outil',
    description: 'Execute a tool or function',
    descriptionFr: 'Exécuter un outil ou une fonction',
    icon: Wrench,
    color: 'text-amber-500',
    bgColor: 'bg-amber-500/10',
    borderColor: 'border-amber-500/40',
    defaultConfig: { toolId: '' },
  },
  {
    id: 'MCP',
    label: 'MCP Tool',
    labelFr: 'Outil MCP',
    description: 'Call a registered MCP tool',
    descriptionFr: 'Appeler un outil MCP enregistré',
    icon: Cpu,
    color: 'text-sky-500',
    bgColor: 'bg-sky-500/10',
    borderColor: 'border-sky-500/40',
    defaultConfig: { toolId: '' },
  },
  {
    id: 'CONDITIONAL',
    label: 'Condition',
    labelFr: 'Condition',
    description: 'Branch based on a condition',
    descriptionFr: 'Branchement selon une condition',
    icon: GitFork,
    color: 'text-sky-500',
    bgColor: 'bg-sky-500/10',
    borderColor: 'border-sky-500/40',
    defaultConfig: { condition: '' },
  },
  {
    id: 'TRANSFORM',
    label: 'Transform',
    labelFr: 'Transformer',
    description: 'Transform or map data',
    descriptionFr: 'Transformer ou mapper des données',
    icon: Shuffle,
    color: 'text-orange-500',
    bgColor: 'bg-orange-500/10',
    borderColor: 'border-orange-500/40',
    defaultConfig: { template: '' },
  },
  {
    id: 'PROMPT',
    label: 'Prompt',
    labelFr: 'Prompt',
    description: 'Provide a template prompt',
    descriptionFr: 'Fournir un prompt modèle',
    icon: MessageSquare,
    color: 'text-cyan-500',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/40',
    defaultConfig: { prompt: '' },
  },
  {
    id: 'TEXT',
    label: 'Text Node',
    labelFr: 'Nœud Texte',
    description: 'Insert raw text block',
    descriptionFr: 'Insérer un bloc de texte brut',
    icon: Type,
    color: 'text-indigo-500',
    bgColor: 'bg-indigo-500/10',
    borderColor: 'border-indigo-500/40',
    defaultConfig: { text: '' },
  },
  {
    id: 'FILE',
    label: 'File',
    labelFr: 'Fichier',
    description: 'Load a file (image, pdf, txt, md)',
    descriptionFr: 'Charger un fichier (image, pdf, txt, md)',
    icon: File,
    color: 'text-pink-500',
    bgColor: 'bg-pink-500/10',
    borderColor: 'border-pink-500/40',
    defaultConfig: { files: [] },
  },
  {
    id: 'LOOP',
    label: 'Loop',
    labelFr: 'Boucle',
    description: 'Iterate over an array and transform each item',
    descriptionFr: 'Itérer sur un tableau et transformer chaque élément',
    icon: Repeat2,
    color: 'text-teal-500',
    bgColor: 'bg-teal-500/10',
    borderColor: 'border-teal-500/40',
    defaultConfig: {
      collection: '',
      itemScript: 'return item;',
      filterScript: '',
      maxIterations: 100,
    },
  },
  {
    id: 'GITHUB',
    label: 'GitHub API',
    labelFr: 'API GitHub',
    description: 'Execute requests against the GitHub REST API',
    descriptionFr: "Exécuter des requêtes vers l'API GitHub",
    icon: Github,
    color: 'text-neutral-500 dark:text-neutral-300',
    bgColor: 'bg-neutral-500/10 dark:bg-neutral-300/10',
    borderColor: 'border-neutral-500/40 dark:border-neutral-300/40',
    defaultConfig: { token: '', endpoint: '/user', method: 'GET', body: '' },
  },
  {
    id: 'SLACK',
    label: 'Slack Message',
    labelFr: 'Message Slack',
    description: 'Post a message to a Slack channel',
    descriptionFr: 'Publier un message sur un canal Slack',
    icon: MessageCircle,
    color: 'text-rose-600',
    bgColor: 'bg-rose-500/10',
    borderColor: 'border-rose-500/40',
    defaultConfig: { token: '', channel: '', message: '' },
  },
  {
    id: 'WHATSAPP',
    label: 'WhatsApp',
    labelFr: 'WhatsApp',
    description: 'Send a WhatsApp message via Cloud API',
    descriptionFr: 'Envoyer un message WhatsApp via Cloud API',
    icon: Phone,
    color: 'text-green-500',
    bgColor: 'bg-green-500/10',
    borderColor: 'border-green-500/40',
    defaultConfig: { token: '', phoneNumberId: '', to: '', message: '' },
  },
  {
    id: 'SHELL',
    label: 'Shell Execute',
    labelFr: 'Script Shell',
    description: 'Execute a shell command locally',
    descriptionFr: 'Exécuter une commande shell localement',
    icon: Terminal,
    color: 'text-zinc-500',
    bgColor: 'bg-zinc-500/10',
    borderColor: 'border-zinc-500/40',
    defaultConfig: { command: 'echo "Hello World"', timeout: 30000 },
  },
  {
    id: 'WORKSPACE_READ',
    label: 'Workspace Read',
    labelFr: 'Lire Espace de Travail',
    description: 'Read a file from the currently open local workspace',
    descriptionFr: "Lire un fichier depuis l'espace de travail local ouvert",
    icon: HardDriveDownload,
    color: 'text-lime-500',
    bgColor: 'bg-lime-500/10',
    borderColor: 'border-lime-500/40',
    defaultConfig: { workspaceId: '', filePath: '' },
  },
  {
    id: 'WORKSPACE_WRITE',
    label: 'Workspace Write',
    labelFr: 'Écrire Espace de Travail',
    description: 'Write content to a file in the currently open local workspace',
    descriptionFr: "Écrire du contenu dans un fichier de l'espace de travail local",
    icon: HardDriveUpload,
    color: 'text-fuchsia-500',
    bgColor: 'bg-fuchsia-500/10',
    borderColor: 'border-fuchsia-500/40',
    defaultConfig: { workspaceId: '', filePath: '', content: '' },
  },
  {
    id: 'SUBWORKFLOW',
    label: 'Sub-Workflow',
    labelFr: 'Sous-Workflow',
    description: 'Call another workflow as a reusable sub-process',
    descriptionFr: 'Appeler un autre workflow comme sous-processus réutilisable',
    icon: Workflow,
    color: 'text-blue-500',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/40',
    defaultConfig: { workflowId: '', inputMapping: {}, outputMapping: {} },
  },
  {
    id: 'ORCHESTRATOR',
    label: 'Orchestrator',
    labelFr: 'Orchestrateur',
    description: 'Loop an agent with auto-spawned sub-agents and retry logic',
    descriptionFr: 'Boucler un agent avec des sous-agents auto-générés et logique de réessai',
    icon: Network,
    color: 'text-indigo-500',
    bgColor: 'bg-indigo-500/10',
    borderColor: 'border-indigo-500/40',
    defaultConfig: {
      agentId: '',
      nodePrompt: '',
      maxIterations: 10,
      maxRetries: 3,
      retryBackoffMs: 1000,
      terminateWhen: '',
      subAgentStrategy: 'auto',
      continueOnSubAgentFailure: false,
      toolIds: [],
      subAgents: [],
      maxTokens: 0,
    },
  },
  {
    id: 'DOWNLOAD_FILE',
    label: 'Download File',
    labelFr: 'Télécharger Fichier',
    description: 'Download a file from a URL and save it to the workspace',
    descriptionFr: 'Télécharger un fichier depuis une URL et le sauvegarder dans le workspace',
    icon: Download,
    color: 'text-cyan-600',
    bgColor: 'bg-cyan-600/10',
    borderColor: 'border-cyan-600/40',
    defaultConfig: { url: '', outputPath: '', filename: '', headers: '' },
  },
  {
    id: 'WHILE',
    label: 'While Loop',
    labelFr: 'Boucle While',
    description: 'Repeat downstream nodes while a condition is true',
    descriptionFr: "Répéter les nœuds en aval tant qu'une condition est vraie",
    icon: RefreshCcw,
    color: 'text-teal-500',
    bgColor: 'bg-teal-500/10',
    borderColor: 'border-teal-500/40',
    defaultConfig: { condition: '', maxIterations: 100 },
  },
  {
    id: 'SWITCH',
    label: 'Switch',
    labelFr: 'Switch',
    description: 'Route to one of multiple branches based on a value',
    descriptionFr: 'Router vers une branche selon une valeur',
    icon: SplitSquareHorizontal,
    color: 'text-amber-500',
    bgColor: 'bg-amber-500/10',
    borderColor: 'border-amber-500/40',
    defaultConfig: { switchOn: '', cases: [] },
  },
  {
    id: 'JSON',
    label: 'JSON',
    labelFr: 'JSON',
    description: 'Inject a static JSON object into the workflow',
    descriptionFr: 'Injecter un objet JSON statique dans le workflow',
    icon: Braces,
    color: 'text-yellow-500',
    bgColor: 'bg-yellow-500/10',
    borderColor: 'border-yellow-500/40',
    defaultConfig: { json: '{}' },
  },
  {
    id: 'EMAIL',
    label: 'Email',
    labelFr: 'Email',
    description: 'Send or manipulate emails',
    descriptionFr: 'Envoyer ou manipuler des emails',
    icon: Mail,
    color: 'text-rose-400',
    bgColor: 'bg-rose-400/10',
    borderColor: 'border-rose-400/40',
    defaultConfig: {
      action: 'send',
      to: '', from: '', subject: '', body: '', html: '',
      attachments: '',
      smtpHost: '', smtpPort: '', smtpUser: '', smtpPass: '',
      mailbox: '', query: '', limit: 20,
      manipulateAction: 'mark_read', uids: '', targetMailbox: '',
      imapUser: '', imapPass: '', imapHost: '', imapPort: '',
    },
  },
  {
    id: 'DOCUMENT',
    label: 'Document',
    labelFr: 'Document',
    description: 'Generate, read, write, or delete documents (PDF, DOCX, XLSX…)',
    descriptionFr: 'Générer, lire, écrire ou supprimer des documents (PDF, DOCX, XLSX…)',
    icon: FileText,
    color: 'text-blue-500',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/40',
    defaultConfig: {
      action: 'generate',
      format: 'pdf',
      title: '',
      author: '',
      sections: '',
      table: '',
      outputPath: '',
      path: '',
      encoding: 'utf-8',
      content: '',
    },
  },
  {
    id: 'FOR_EACH',
    label: 'For Each',
    labelFr: 'Pour Chaque',
    description: 'Run downstream nodes for every item in an array and collect results',
    descriptionFr: 'Exécuter les nœuds suivants pour chaque élément d\'un tableau et collecter les résultats',
    icon: ListOrdered,
    color: 'text-cyan-500',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/40',
    defaultConfig: { collection: '', outputKey: '', maxIterations: 100 },
  },
];

export const getNodeTypeMeta = (type: NodeTypeId | string): NodeTypeMeta =>
  NODE_TYPE_REGISTRY.find((n) => n.id === type) ?? NODE_TYPE_REGISTRY[0];
