export class Collection {
  constructor(
    public readonly id: string,
    public readonly name: string,
    public readonly userId: string,
    public readonly dimension: number,
    public readonly distance: 'cosine' | 'euclidean' | 'dot',
    public readonly createdAt: Date,
    public readonly updatedAt: Date,
  ) {}

  public getQdrantCollectionName(): string {
    return `${this.userId}_${this.name}`;
  }

  public static create(
    name: string,
    userId: string,
    dimension: number,
    distance: 'cosine' | 'euclidean' | 'dot' = 'cosine',
  ): Collection {
    return new Collection(
      '', // ID will be generated by database
      name,
      userId,
      dimension,
      distance,
      new Date(),
      new Date(),
    );
  }
}
